integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
backend:
  database:
    client: pg
    connection:
      host: ${HOST}
      port: ${PORT}
      user: ${USERNAME}
      password: ${PASSWORD}
      database: ${DATABASE}
